kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: devops-fusion-sample-pipeline
spec:
  source:
    git:
      uri: [THE_URI_OF_YOUR_GIT_REPO]
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile.groovy
      env:
      - name: OPENSHIFT_NAMESPACE
        value: [THE_NAME_OF_YOUR_OPENSHIFT_PROJECT]
    type: JenkinsPipeline