kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: devops-fusion-sample-pipeline
spec:
  source:
    git:
      uri: https://github.com/lehmamic/openshift-test
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile.groovy
      env:
      - name: OPENSHIFT_NAMESPACE
        value: devopsfusionleh
    type: JenkinsPipeline