apiVersion: v1
kind: Template
metadata:
  labels:
    app: demo-app-docker
  name: demo-app-docker
parameters:
- name: DOCKER_IMAGE_TAG
  required: true

objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: demo-app-docker
    name: demo-app-docker
  spec:
    source:
      contextDir: .
      type: Binary
    output:
      to:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/demo-app:1.0.0.0
    runPolicy: Parallel
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: registry.redhat.io/dotnet/dotnet-31-rhel7
        pullSecret:
          name: image-pull-secret
        env:
        - name: "DISABLE_ASSET_COMPILATION"
          value: "true"
      type: Source